change jenkins updater

diff --git a/jenkinsfile_updaterhalt b/jenkinsfile_updaterhalt
--- a/jenkinsfile_updaterhalt
+++ b/jenkinsfile_updaterhalt
@@ -39,12 +39,14 @@ pipeline {
             }
             steps {
                 echo ("env Ma chung khoan: ${inputMa}" )
-                sh 'curl "http://192.168.54.7:8880/admin" -X POST   -d "{ \"RType\":\"UpdateStock\", \"StockSymbol\": \"{inputMa}\", \"HaltResumeFlag\": \"H\"}"&& echo "Success" || echo "Failure"'
+                def postcommand = \"RType\":\"UpdateStock\", \"StockSymbol\": \"${inputMa}\", \"HaltResumeFlag\": \"H\"
+                echo ("env command: ${postcommand}" )
+                sh 'curl "http://192.168.54.7:8880/admin" -X POST   -d "{${postcommand}}"&& echo "Success" || echo "Failure"'
             }
             post {
                 success {
                     ansiColor('xterm'){
-                    echo 'Halt lô chẵn mã {inputMa} thành công!'
+                     echo ("Halt lô chẵn mã ${inputMa} thành công!" )   
                     }
                 }
             }
