new jekinfile updater

diff --git a/jenkinsfile_updaterhalt b/jenkinsfile_updaterhalt
--- a/jenkinsfile_updaterhalt
+++ b/jenkinsfile_updaterhalt
@@ -1,7 +1,7 @@
-pipeline {  
+pipeline {
     agent any
     stages {
-		 stage('input OTWS') {
+         stage('input OTWS') {
                 environment {
                     inputMa = ''
                     inputType = ''
@@ -28,8 +28,8 @@ pipeline {
                     echo ("env Trang thai Halt: ${ inputType}" )
                     echo ("env Loai: ${ inputLoai}" )
                     }
-                    }
                 }
+         }
         stage('Halt lô chẵn') {
             when {
                 allOf {
@@ -39,17 +39,18 @@ pipeline {
             }
             steps {
                 echo ("env Ma chung khoan: ${inputMa}" )
-                sh 'curl "http://192.168.54.7:8880/admin" -X POST -d "{RType:UpdateStock, StockSymbol: ${env.inputMa}, HaltResumeFlag: H}" && echo "Success" || echo "Failure"'            }
-            }
+                sh 'curl "http://192.168.54.7:8880/admin" -X POST -d "{RType:UpdateStock, StockSymbol: ${env.inputMa}, HaltResumeFlag: H}" && echo "Success" || echo "Failure"'           
+                }
+        
             post {
                 success {
                     ansiColor('xterm'){
-                     echo ("Halt lô chẵn mã ${inputMa} thành công!" )   
+                     echo ("Halt lô chẵn mã ${inputMa} thành công!" )
                     }
                 }
             }
             }
-    
+
             stage('Halt lô lẻ') {
             when {
                 allOf {
@@ -58,9 +59,10 @@ pipeline {
                 }
             }
             steps {
-                sh 'curl "http://192.168.54.7:8880/admin" -X POST -d "{RType:UpdateStock, StockSymbol: ${env.inputMa}, altResumeFlagOddLot: H}" && echo "Success" || echo "Failure"'            }
+                sh 'curl "http://192.168.54.7:8880/admin" -X POST -d "{RType:UpdateStock, StockSymbol: ${env.inputMa}, altResumeFlagOddLot: H}" && echo "Success" || echo "Failure"' 
 
-                //sh 'curl "http://192.168.54.7:8880/admin" -X POST   -d "{ \"RType\":\"UpdateStock\", \"StockSymbol\": \"${inputMa}\", \"HaltResumeFlagOddLot\": \"H\"}" && echo "Success" || echo "Failure"'
+            //sh 'curl "http://192.168.54.7:8880/admin" -X POST   -d "{ \"RType\":\"UpdateStock\", \"StockSymbol\": \"${inputMa}\", \"HaltResumeFlagOddLot\": \"H\"}" && echo "Success" || echo "Failure"'
+
             }
             post {
                 success {
@@ -69,7 +71,7 @@ pipeline {
                     }
                 }
             }
-            }
+            }       
             stage('Halt lô chẵn và lô lẻ') {
             when {
                 allOf {
@@ -132,7 +134,7 @@ pipeline {
                 }
             }
             steps {
-                sh 'curl "http://192.168.54.7:8880/admin" -X POST   -d "{ \"RType\":\"UpdateStock\", \"StockSymbol\": \"${inputMa}\", \"HaltResumeFlag\": \"\", \"HaltResumeFlagOddLot\": \"\"}" && echo "Success" || echo "Failure"'  
+                sh 'curl "http://192.168.54.7:8880/admin" -X POST   -d "{ \"RType\":\"UpdateStock\", \"StockSymbol\": \"${inputMa}\", \"HaltResumeFlag\": \"\", \"HaltResumeFlagOddLot\": \"\"}" && echo "Success" || echo "Failure"'
             }
             post {
                 success {
@@ -142,7 +144,9 @@ pipeline {
                 }
             }
             }
-
-        }
     }
+}
+
+        
+    
 
