new jekinfile updater

diff --git a/jenkinsfile_updaterhalt b/jenkinsfile_updaterhalt
--- a/jenkinsfile_updaterhalt
+++ b/jenkinsfile_updaterhalt
@@ -59,11 +59,11 @@ pipeline {
                 }
             }
             steps {
-                echo ' Ma: ${inputMa} '
+                echo ("env Ma chung khoan: ${inputMa}" )
                 //sh 'curl "http://192.168.54.7:8880/admin" -X POST -d "{RType:UpdateStock, StockSymbol: ${env.inputMa}, HaltResumeFlagOddLot: H}" && echo "Success" || echo "Failure"' 
 
-            sh 'curl "http://192.168.54.7:8880/admin" -X POST   -d "{ \"RType\":\"UpdateStock\", \"StockSymbol\": \"$env.${inputMa}\", \"HaltResumeFlagOddLot\": \"H\"}" && echo "Success" || echo "Failure"'
-
+            sh 'curl "http://192.168.54.7:8880/admin" -X POST   -d "{ \"RType\":\"UpdateStock\", \"StockSymbol\": \"env.inputMa\", \"HaltResumeFlagOddLot\": \"H\"}" && echo "Success" || echo "Failure"'
+String 
             }
             post {
                 success {
